version: "3.7"
services:
  app:
    build:
      args:
        user: rafflebird
        uid: 1000
      context: ./
    image: rafflebird
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - rafflebird

networks:
  rafflebird:
    driver: bridge
